### ISSUE TITLE
manifest.json提示”缺少属性xxx“

### ISSUE THREAD

**Issue by wzj2014** [uni-helper/uni-app-schemas-vscode#20]
### 描述问题

安装插件后，manifest.json文件会提示”缺少属性xxx“
期望：这些属性不配置，不提示警告

![image](https://github.com/uni-helper/uni-app-schemas-vscode/assets/7589685/ffe03d9c-2af4-4ef1-85c4-014b8a7b28d4)

### 复现

安装插件
重启vscode
打开项目的manifest.json文件

### 系统信息

```Shell
bogon:list-uniapp wangzhenjie$ npx envinfo --system --binaries --browsers

  System:
    OS: macOS 13.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 66.19 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 8.11.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 16.6
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
方便切换到 0.8.11 并 reload window 吗？0.8.11 是否有这个问题？

**Comment by codeflyA** [comment]
一样

**Comment by bamf2077** [comment]
> 方便切换到 0.8.11 并 reload window 吗？0.8.11 是否有这个问题？

你们自己真的有在 VSCode 中用过这个 JSON 构架文件吗？一打开 `manifest.json` 就是几十条警告。

以 `manifest.json` 文件中 `mp-weixin > setting` 部分为例，JSON 架构文件将微信小程序所有的配置属性全都列入了 `required` 必选条目，这些内容应该全部都是可选，所以导致了现在只要漏写一个就报错。

```json
{
  "required": [
    "es6",
    "es7",
    "enhance",
    "postcss",
    "minified",
    "minifyWXSS",
    "minifyWXML",
    "uglifyFileName",
    "ignoreUploadUnusedFiles",
    "autoAudits",
    "urlCheck",
    "compileHotReLoad",
    "preloadBackgroundData",
    "lazyloadPlaceholderEnable",
    "useStaticServer",
    "bigPackageSizeSupport",
    "babelSetting",
    "useCompilerPlugins",
    "disableUseStrict",
    "uploadWithSourceMap",
    "localPlugins",
    "packNpmManually",
    "packNpmRelationList",
    "coverView",
    "ignoreDevUnusedFiles",
    "checkInvalidKey",
    "showShadowRootInWxmlPanel",
    "useIsolateContext",
    "useMultiFrameRuntime",
    "useApiHook",
    "useApiHostProcess",
    "useLanDebug",
    "enableEngineNative",
    "showES6CompileOption",
    "checkSiteMap"
  ]
}
```

最外层的属性也是一样，必选属性只有 `appid`，其他都应该是可选，现在是所有平台的配置都要写，不然就警告说你漏写了。

```json
{
  "required": [
    "app-plus",
    "appid",
    "debug",
    "description",
    "h5",
    "locale",
    "mp-alipay",
    "mp-baidu",
    "mp-kuaishou",
    "mp-lark",
    "mp-qq",
    "mp-toutiao",
    "mp-weixin",
    "name",
    "networkTimeout",
    "quickapp-webview",
    "quickapp-webview-huawei",
    "quickapp-webview-union",
    "transformPx",
    "uniStatistics",
    "versionCode",
    "versionName"
  ]
}
```

最简单的解决办法，删除全部的 `required` 字段。

**Comment by ModyQyW** [comment]
> 你们真的有在 VSCode 中用过这个 JSON 构架文件吗？一打开 manifest.json 就是几十条警告。

你真的有看 README 吗？**插件和文档的冲突之处，请以文档为准。**更何况你总是可以回退插件版本，或者卸载插件使用旧的 JSON schema。

我们不是只做 uni-app 的开发人员，不会时时刻刻都在做 uni-app，更别说现在大家都是没有精力时间的状态。uni-app 那边没给我们开全职工资，你也没给我们开全职工资。有问题就说问题，谁有空了就会来修。比起在这里抱怨我们没时间没精力，我们更欢迎 PR。你这种发言真的很不负责任，我们不欢迎类似的发言，谢谢。

**Comment by bamf2077** [comment]
> > 你们真的有在 VSCode 中用过这个 JSON 构架文件吗？一打开 manifest.json 就是几十条警告。
> 
> 你真的有看 README 吗？**插件和文档的冲突之处，请以文档为准。**更何况你总是可以回退插件版本，或者卸载插件使用旧的 JSON schema。
> 
> 我们不是只做 uni-app 的开发人员，不会时时刻刻都在做 uni-app，更别说现在大家都是没有精力时间的状态。uni-app 那边没给我们开全职工资，你也没给我们开全职工资。有问题就说问题，谁有空了就会来修。比起在这里抱怨我们没时间没精力，我们更欢迎 PR。你这种发言真的很不负责任，我们不欢迎类似的发言，谢谢。

已经在写 PR 了，又不是指责你，发布前至少测试一下难道不是正常流程吗？

**Comment by ModyQyW** [comment]
为什么你会觉得这不是指责？是以你的感觉为准吗？

为什么你会觉得我们没有测试一下？大家的测试文件千差万别，谁敢保证测试一定完全覆盖了？
